name: Build and deploy Next.js app to Azure Web App - land

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json .next
          npm ci

      - name: Verify component imports (prevent missing module errors)
        run: |
          ls -R ./app/components

      - name: Build Next.js app
        run: npm run build

      - name: Zip artifact for deployment
        run: zip -r release.zip .next public package.json package-lock.json node_modules

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F6FBDF13D9914B76BC1C9E672E553668 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8CA3A3703CBF406595EEAEBBC7156A6C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D9EEC93DC5644A21BBACEFB331228203 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'land'
          slot-name: 'Production'
          package: .
          
